version: 2
multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Amsterdam"
    labels:
      - "dependencies"
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    labels:
      - "github-actions"
    multi-ecosystem-group: "dependencies"
  - package-ecosystem: "pre-commit"
    directory: "/"
    patterns:
      - "*"
    cooldown:
      default-days: 7
    multi-ecosystem-group: "dependencies"
  - package-ecosystem: "pip"
    directory: "/"
    patterns:
      - "*"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    open-pull-requests-limit: 5
    labels:
      - "python"
    multi-ecosystem-group: "dependencies"
