github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"

schema:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**/schema*"
          - "src/**/*schema*"
          - "src/**/*.json"
