name-template: "Release $RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (@$AUTHOR)"
sort-direction: ascending
exclude-labels:
  - "skip-changelog"
categories:
  - title: "Breaking"
    labels:
      - "breaking"
  - title: "Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "Testing"
    labels:
      - "tests"
  - title: "Documentation"
    labels:
      - "docs"
  - title: "Chores"
    labels:
      - "chore"
      - "ci"
      - "build"
version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "bug"
      - "fix"
  default: patch
template: |
  ## Changes
  $CHANGES
