repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-check
        args:
          - --cache-dir
          - /tmp/ruff-cache
          - --fix
      - id: ruff-format
        args:
          - --cache-dir
          - /tmp/ruff-cache
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.30.0
    hooks:
      - id: zizmor
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args:
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types: [csv, json, html]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: no-commit-to-branch
        args:
          - --branch=main
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: bash scripts/run-uv-tool.sh pyright
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: bash scripts/run-uv-tool.sh pytest
        language: system
        pass_filenames: false
